Filmat/Controllers/LogsController.cs
using Filmat.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Filmat.Controllers
{
	[Authorize(Roles = "Admin")]
	public class LogsController : Controller
	{

		private readonly AppDbContext _context;

		public LogsController(AppDbContext context)
		{
			_context =	context;
		}
		public async Task<IActionResult> Index()
		{
			var logs = await _context.Logs.ToListAsync();

			return View(logs);
		}
	}
}

Filmat/Controllers/LogsatController.cs
using Filmat.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Filmat.Controllers
{
	[Authorize(Roles = "Admin")]
	public class LogsatController : Controller
	{

		private readonly AppDbContext _context;

		public LogsatController(AppDbContext context)
		{
			_context =	context;
		}
		public async Task<IActionResult> Index()
		{
			var logs = await _context.Logs.ToListAsync();

			return View(logs);
		}
	}
}

Filmat/Views/Logsat/Index.cshtml
@model IEnumerable<Logs>

@{
    ViewData["Title"] = "List of Movies";

    //  Pager pager = new Pager();

    //int pageNo = 0;

    //if(ViewBag.Pager != null)
    //{
    //    pager = ViewBag.Pager;
    //    pageNo = pager.CurrentPage;
    //}
}

@section Styles{
    <link href="@Url.Content("~/css/StyleSheet.css")" rel="stylesheet" />

}



    <h3 style="color: white">Logs for Users and Movies:</h3>
<br />
<br />
<br />

<table class="table">



    <thead>
        <tr>
            <th style="color:white" scope="col">Actor</th>
            <th style="color:white" scope="col">Action</th>
            <th style="color:white" scope="col">Entity</th>
            <th style="color:white" scope="col">Name</th>
            <th style="color:white" scope="col">Date/Time</th>
        </tr>
    </thead>


    <tbody style="border:1.5px solid white">

        @foreach (var item in Model)
        {




            if (item.Item.Equals("AdministrationController"))
            {

                if (item.Action.Equals("Create"))
                {
                    <tr class="table-success">
                        <th scope="row">@item.User</th>
                        <th>Created</th>
                        <th>User</th>
                        <th>@item.Details</th>
                        <th>@item.Timestamp</th>
                    </tr>
                }

                if (item.Action.Equals("Update"))
                {
                    <tr class="table-warning">
                        <th scope="row">@item.User</th>
                        <th>Updated</th>
                        <th>User</th>
                        <th>@item.Details</th>
                        <th>@item.Timestamp</th>
                    </tr>
                }
                if (item.Action.Equals("Delete"))
                {
                    <tr class="table-danger">
                        <th scope="row">@item.User</th>
                        <th>Deleted</th>
                        <th>User</th>
                        <th>@item.Details</th>
                        <th>@item.Timestamp</th>
                    </tr>

                }


            }

            if (item.Item.Equals("MoviesController"))
            {

                if (item.Action.Equals("Create"))
                {
                    <tr class="table-success">
                        <th scope="row">@item.User</th>
                        <th>Created</th>
                        <th>Movie</th>
                        <th>@item.Details</th>
                        <th>@item.Timestamp</th>
                    </tr>
                }

                if (item.Action.Equals("Update"))
                {
                    <tr class="table-warning">
                        <th scope="row">@item.User</th>
                        <th>Updated</th>
                        <th>Movie</th>
                        <th>@item.Details</th>
                        <th>@item.Timestamp</th>
                    </tr>
                }
                if (item.Action.Equals("Delete"))
                {
                    <tr class="table-danger">
                        <th scope="row">@item.User</th>
                        <th>Deleted</th>
                        <th>Movie</th>
                        <th>@item.Details</th>
                        <th>@item.Timestamp</th>
                    </tr>

                }


            }




        }


    </tbody>


</table>

@* <div class="container"> asdasdadasd
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Logs" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Logs" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                </li>
            }


            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Logs" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>

            }
            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Logs" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Logs" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            }


        </ul>
    }
</div>*@