Filmat/Controllers/LogsatController.cs
using Filmat.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Filmat.Controllers
{
	[Authorize(Roles = "Admin")]
	public class LogsatController : Controller
	{

		private readonly AppDbContext _context;

		public LogsatController(AppDbContext context)
		{
			_context =	context;
		}
		public async Task<IActionResult> Index()
		{
			var logs = await _context.Logs.ToListAsync();

			return View(logs);
		}
	}
}

Filmat/Controllers/MoviesController.cs
using Filmat.Areas.Identity.Data;
using Filmat.Data;
using Filmat.Data.Services;
using Filmat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace Filmat.Controllers
{

	[Authorize]
	public class MoviesController : Controller
	{
		private readonly IMoviesService _service;
		private readonly SignInManager<ApplicationUser> signInManager;

		public MoviesController(IMoviesService service, SignInManager<ApplicationUser> signInManager)
		{
			_service = service;
			this.signInManager = signInManager;
		}



		public async Task<IActionResult> Index(int pg = 1)
		{
			var data = await _service.GetAllAsync();

			const int pageSize = 5;

			if (pg < 1)
			{
				pg = 1;
			}

			int recsCount = data.Count(); // sa rekorde jon

			var pager = new Pager(recsCount, pg, pageSize);

			int recSkip = (pg - 1) * pageSize;

			var data2 = data.Skip(recSkip).Take(pager.PageSize).ToList(); // sa recorde kan mu bo skip (per me display recorded n'faqen perkatese)

			this.ViewBag.Pager = pager;


			return View(data2);



		}
		[Authorize]
		//Get: Clients/Create
		public IActionResult Create()
		{
			return View();
		}
		[Authorize]
		[HttpPost]
		public async Task<IActionResult> Create(Movie movie)
		{
			if (!ModelState.IsValid)
			{
				return View(movie);
			}
			_service.LogAction("Create", User: User.Identity.Name, details: movie.Name, item: nameof(MoviesController));
			await _service.AddAsync(movie);





			return RedirectToAction(nameof(Index));
		}

		//Get:  Clients/Details/1

		public async Task<IActionResult> Details(int id)
		{
			var movieDetails = await _service.GetByIdAsync(id);

			if (movieDetails == null) return View("NotFound");
			return View(movieDetails);
		}


		//Get: Clients/Edit
		public async Task<IActionResult> Edit(int id)
		{
			var movieDetails = await _service.GetByIdAsync(id);
			if (movieDetails == null) return View("NotFound");
			return View(movieDetails);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, [Bind("Name,Description,MovieCategory,ImageURL,VideoURL")] Movie movie)
		{
			if (!ModelState.IsValid)
			{
				return View(movie);
			}
			await _service.UpdateAsync(id, movie);
			_service.LogAction("Update", User: User.Identity.Name, details: movie.Name, item: nameof(MoviesController));
			return RedirectToAction(nameof(Index));
		}


		public async Task<IActionResult> Delete(int id)
		{
			var movieDetails = await _service.GetByIdAsync(id);
			if (movieDetails == null) return View("NotFound");
			return View(movieDetails);
		}

		[HttpPost]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var movieDetails = await _service.GetByIdAsync(id);
			if (movieDetails == null) return View("NotFound");

			_service.LogAction("Delete", User: User.Identity.Name, details: movieDetails.Name, item: nameof(MoviesController));
			await _service.DeleteAsync(id);


			return RedirectToAction(nameof(Index));
		}




		public async Task<IActionResult> PlayMovie(int id)
		{
			var movie = await _service.GetByIdAsync(id);



			if (movie == null)
			{
				ViewBag.ErrorMessage = $"Movie with Id = {id} cannot be found";
				return View("NotFound");
			}
			else
			{

				movie.ViewCount++;
				await _service.UpdateAsync(id, movie);
				return View(movie);

			}

		}

		[HttpGet]
		public async Task<ActionResult> MoviesByCategory(string category)
		{
			var movies = await _service.GetAllAsync();
			var mc = movies.Where(m => m.MovieCategory.ToString().Equals(category));
			return View(mc);
		}


		[HttpPost]
		public IActionResult Search(string searchQuery)
		{
			

			var movies = _service.SearchMovies(searchQuery);

			
				return View(movies); 

		}



	}
	
			
			
}

Filmat/Views/Movies/AccessDenied.cshtml
@{
	Layout = null;
}

<h1>Movie Was Not Found! </h1>

Filmat/Views/Movies/Create.cshtml
@model Movie

@{
    ViewData["Title"] = "Add a new movie";
}

@section Styles{
    <link href="@Url.Content("~/css/PlayMovie.css")" rel="stylesheet" />

}


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
                <h1 style="color: white">Add New Movie</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label style="color:white" asp-for="ImageURL" class="control-label"></label>
                        <input asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label style="color:white" asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label style="color:white" asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label style="color:white" asp-for="Duration" class="control-label"></label>
                        <input asp-for="Duration" class="form-control" />
                        <span asp-validation-for="Duration" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label style="color:white" asp-for="MovieCategory" class="control-label"></label>
                        <input asp-for="MovieCategory" class="form-control" />
                        <span asp-validation-for="MovieCategory" asp-items="Html.GetEnumSelectList<MovieCategory>()" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label style="color:white" asp-for="VideoURL" class="control-label"></label>
                        <input asp-for="VideoURL" class="form-control" />
                        <span asp-validation-for="VideoURL" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                            <input  type="submit" asp-action="Create" value="Create" class="btn btn-outline-success float-right" />
                            <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ImageURL").val();
        })
        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Filmat/Views/Movies/Delete.cshtml
@model Movie

@{
    ViewData["Title"] = "Delete movie";
}

@section Styles{
    <link href="@Url.Content("~/css/StyleSheet.css")" rel="stylesheet" />

}


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete movie: @Model.Name ?</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                
                <div class="form-group text-center">
                    <img id="ProfilePicturePreview" class="border-info rounded-circle" style="max-width: 150px" />
                </div>
                <div class="form-group">
                    <label asp-for="ImageURL" class="control-label"></label>
                    <input asp-for="ImageURL" class="form-control" disabled />
                    <span asp-validation-for="ImageURL" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" disabled />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" disabled />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Duration" class="control-label"></label>
                    <input asp-for="Duration" class="form-control" disabled />
                    <span asp-validation-for="Duration" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MovieCategory" class="control-label"></label>
                    <input asp-for="MovieCategory" class="form-control" disabled />
                    <span asp-validation-for="MovieCategory" asp-items="Html.GetEnumSelectList<MovieCategory>()" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="VideoURL" class="control-label"></label>
                    <input asp-for="VideoURL" class="form-control" disabled />
                    <span asp-validation-for="VideoURL" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <form asp-action="DeleteConfirmed">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                    </form>
                    @*<a type="submit" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-success float-right">Confirm</a>*@
                    <a class="btn btn-outline-secondary" asp-action="Index">Decline</a>
                </div>
                

            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ImageURL").val();
        })
        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Filmat/Views/Movies/Index.cshtml
@model IEnumerable<Movie>
@inject SignInManager<ApplicationUser> signInManager;


@{
    ViewData["Title"] = "List of Movies";
    Layout = null;
    Pager pager = new Pager();

    int pageNo = 0;

    if(ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage; 
    }
} 


<link href="@Url.Content("~/css/moviesFinal.css")" rel="stylesheet" /> 
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class="banner">
    <div class="navbar">
        <img src="~/images/logofinal2.png" class="logo" />
        <ul>
            @if (signInManager.IsSignedIn(User))
            {
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Movies" asp-action="Index">Movies</a></li>
                <li>
                    <div class="dropdown">
                        <button>Categories</button>
                        <div class="dropdown-options">
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Action">Action</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Comedy">Comedy</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Drama">Drama</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="horror">Horror</a>
                        </div>
                    </div>
                </li>
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {

                     <li><a asp-controller="Administration" asp-action="ListUsers">Users</a></li>
                     <li><a asp-controller="Administration" asp-action="ListRoles">Roles</a></li>
                     <li><a asp-controller="Logsat" asp-action="Index">Logs</a></li>

                }
                
                <li>
                    <form method="post" asp-action="Logout" asp-controller="Account">
                        <button class="buttoni" type="submit">
                            Logout @User.Identity.Name
                        </button>
                    </form>
                </li>
            }
        </ul>
    </div>

    <form method="post" asp-action="Search" class="form-inline my-2 my-lg-0 display-left">
        <input name="searchQuery" style=" color:white; margin-left:38%;background:transparent; border:0.5px solid white;" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button style="margin-top:0.7534983853606028vh; margin-bottom:0.5%" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <div class="most-watched">
            @foreach (var item in Model)
            { 
                <div style="padding-bottom:5%">
                <a asp-controller="Movies" asp-action="PlayMovie" asp-route-id="@item.Id">
                    <div class="frem">
                        <div class="center-cant">
                            <img src="@item.ImageURL" alt="">
                            <div class="row">
                                <p>@item.Name</p>
                                <h2>@item.ViewCount views</h2>
                            </div>
                        </div>
                    </div>
                </a>
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <div style:"width:auto">
                        <a class="edit" title="Edit" data-toggle="tooltip" asp-action="Edit" asp-route-id="@item.Id"><i class="material-icons">&#xE254;</i></a>
                        <a title="Details" data-toggle="tooltip" asp-action="Details" asp-route-id="@item.Id"><i class="material-icons">&#xE253;</i></a>
                        <a
                        class="delete"
                        title="Delete"
                        data-toggle="tooltip"
                        asp-action="Delete"
                        asp-route-id="@item.Id"
                        >
                        <i class="material-icons">&#xE872;</i>
                        </a>
                        </div>
                    }
                </div>
            }
    </div>
     <div class="container">
            @if (pager.TotalPages > 0)
            {
                <ul class="pagination justify-content-end">

                    @if (pager.CurrentPage > 1)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="1">First</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                        </li>
                    }


                    @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                    {
                        <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@pge">@pge</a>
                        </li>

                    }
                    @if (pager.CurrentPage < pager.TotalPages)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                        </li>
                        <li>
                            <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                        </li>
                    }


                </ul>
            }
        </div>

    <div style="position:fixed; right:25px; bottom:25px;" class="text-white" class="btn-group" role="group" aria-label="Basic example">
            @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
            <button type="button" class="btn btn-secondary">
                <a asp-controller="Movies" asp-action="Create">Add New</a>
              </button>
            }
        <button type="button" class="btn btn-secondary">
            <a asp-controller="Comments" asp-action="Index">Leave a Comment</a>
        </button>
        
    </div>
    

</div>

    







   

Filmat/Views/Movies/MoviesByCategory.cshtml
@model IEnumerable<Movie>
@inject SignInManager<ApplicationUser> signInManager;

@{
    ViewData["Title"] = "Movies by Category";
    Layout = null;
    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

    <link href="@Url.Content("~/css/moviesFinal.css")" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <div class="banner">
        <div class="navbar">
            <img src="~/images/logofinal2.png" class="logo" />
            <ul>
            @if (signInManager.IsSignedIn(User))
            {
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Movies" asp-action="Index">Movies</a></li>
                <li>
                    <div class="dropdown">
                        <button>Categories</button>
                        <div class="dropdown-options">
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Action">Action</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Comedy">Comedy</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Drama">Drama</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="horror">Horror</a>
                        </div>
                    </div>
                </li>
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {

                    <li><a asp-controller="Administration" asp-action="ListUsers">Users</a></li>
                    <li><a asp-controller="Administration" asp-action="ListRoles">Roles</a></li>
                    <li><a asp-controller="Logsat" asp-action="Index">Logs</a></li>

                }

                <li>
                    <form method="post" asp-action="Logout" asp-controller="Account">
                        <button class="buttoni" type="submit">
                            Logout @User.Identity.Name
                        </button>
                    </form>
                </li>
            }
        </ul>
    </div>

    <form method="post" asp-action="Search" class="form-inline my-2 my-lg-0 display-left">
        <input name="searchQuery" style=" color:white; margin-left:38%;background:transparent; border:0.5px solid white;" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button style="margin-top:0.7534983853606028vh; margin-bottom:0.5%" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <div class="most-watched">
        @foreach (var item in Model)
        {
            <div style="padding-bottom:5%">
                <a asp-controller="Movies" asp-action="PlayMovie" asp-route-id="@item.Id">
                    <div class="frem">
                        <div class="center-cant">
                            <img src="@item.ImageURL" alt="">
                            <div class="row">
                                <p>@item.Name</p>
                                <h2>@item.ViewCount views</h2>
                            </div>
                        </div>
                    </div>
                </a>
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <div style:"width:auto">
                        <a class="edit" title="Edit" data-toggle="tooltip" asp-action="Edit" asp-route-id="@item.Id"><i class="material-icons">&#xE254;</i></a>
                        <a title="Details" data-toggle="tooltip" asp-action="Details" asp-route-id="@item.Id"><i class="material-icons">&#xE253;</i></a>
                        <a class="delete"
                   title="Delete"
                   data-toggle="tooltip"
                   asp-action="Delete"
                   asp-route-id="@item.Id">
                            <i class="material-icons">&#xE872;</i>
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="container">
        @if (pager.TotalPages > 0)
        {
            <ul class="pagination justify-content-end">

                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                    </li>
                }


                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </li>

                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li>
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }


            </ul>
        }
    </div>
    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <div style="position:fixed; right:25px; bottom:25px;" class="text-white">
            <a asp-controller="Movies" asp-action="Create" class="btn btn-success"><i style="background: transparent;" class="bg-info bi-plus-circle">Add New</i></a>
        </div>
    }

</div>

Filmat/Views/Movies/Search.cshtml
@model IEnumerable<Movie>
@inject SignInManager<ApplicationUser> signInManager;


@{
    ViewData["Title"] = "List of Movies";
    Layout = null;
    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}
   

    <link href="@Url.Content("~/css/moviesFinal.css")" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <div class="banner">
        <div class="navbar">
            <img src="~/images/logofinal2.png" class="logo" />
            <ul>
            @if (signInManager.IsSignedIn(User))
            {
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Movies" asp-action="Index">Movies</a></li>
                <li>
                    <div class="dropdown">
                        <button>Categories</button>
                        <div class="dropdown-options">
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Action">Action</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Comedy">Comedy</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="Drama">Drama</a>
                            <a asp-controller="Movies" asp-action="MoviesByCategory" asp-route-category="horror">Horror</a>
                        </div>
                    </div>
                </li>
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {

                    <li><a asp-controller="Administration" asp-action="ListUsers">Users</a></li>
                    <li><a asp-controller="Administration" asp-action="ListRoles">Roles</a></li>
                    <li><a asp-controller="Logsat" asp-action="Index">Logs</a></li>

                }

                <li>
                    <form method="post" asp-action="Logout" asp-controller="Account">
                        <button class="buttoni" type="submit">
                            Logout @User.Identity.Name
                        </button>
                    </form>
                </li>
            }
        </ul>
    </div>

    <form method="post" asp-action="Search" class="form-inline my-2 my-lg-0 display-left">
        <input name="searchQuery" style=" color:white; margin-left:38%;background:transparent; border:0.5px solid white;" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button style="margin-top:0.7534983853606028vh; margin-bottom:0.5%" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <div class="most-watched">
        @foreach (var item in Model)
        {
            <div style="padding-bottom:5%">
                <a asp-controller="Movies" asp-action="PlayMovie" asp-route-id="@item.Id">
                    <div class="frem">
                        <div class="center-cant">
                            <img src="@item.ImageURL" alt="">
                            <div class="row">
                                <p>@item.Name</p>
                                <h2>@item.ViewCount views</h2>
                            </div>
                        </div>
                    </div>
                </a>
                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <div style:"width:auto">
                        <a class="edit" title="Edit" data-toggle="tooltip" asp-action="Edit" asp-route-id="@item.Id"><i class="material-icons">&#xE254;</i></a>
                        <a title="Details" data-toggle="tooltip" asp-action="Details" asp-route-id="@item.Id"><i class="material-icons">&#xE253;</i></a>
                        <a class="delete"
                   title="Delete"
                   data-toggle="tooltip"
                   asp-action="Delete"
                   asp-route-id="@item.Id">
                            <i class="material-icons">&#xE872;</i>
                        </a>
                    </div>
                }
            </div>
        }
    </div>
    <div class="container">
        @if (pager.TotalPages > 0)
        {
            <ul class="pagination justify-content-end">

                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                    </li>
                }


                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </li>

                }
                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li>
                        <a class="page-link" asp-controller="Movies" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }


            </ul>
        }
    </div>
    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <div style="position:fixed; right:25px; bottom:25px;" class="text-white">
            <a asp-controller="Movies" asp-action="Create" class="btn btn-success"><i style="background: transparent;" class="bg-info bi-plus-circle">Add New</i></a>
        </div>
    }

</div>